name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Make Go build script executable
        run: chmod +x GoSpoofer/make.sh

      - name: Build GoSpoofer library
        run: |
          cd GoSpoofer
          ./make.sh

      - name: Build iOS app
        run: |
          xcodebuild \
            -project location-spoofer.xcodeproj \
            -scheme location-spoofer \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Create Payload folder
        run: mkdir Payload

      - name: Copy app into Payload
        run: |
          find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d

          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "location-spoofer.app" -type d | head -n 1)

          cp -r "$APP_PATH" Payload/

      - name: Create IPA
        run: |
          zip -r location-spoofer.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: location-spoofer.ipa
