name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List schemes
        run: xcodebuild -project location-spoofer.xcodeproj -list

      - name: Build app
        run: |
          xcodebuild \
            -project location-spoofer.xcodeproj \
            -scheme GoSpoofer \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Create Payload folder
        run: mkdir Payload

      - name: Copy app into Payload
        run: |
          cp -r build/Release-iphoneos/GoSpoofer.app Payload/

      - name: Create IPA
        run: |
          zip -r GoSpoofer.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: GoSpoofer.ipa
